import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  fr: {
    nav: ['Services', 'Devis', 'Zones', 'FAQ'],
    cta: 'Demander un devis',
    hero: {
      eyebrow: 'Plomberie à {city}',
      h1a: 'Plomberie conçue',
      h1b: 'pour durer.',
      sub: '{businessName} prend en charge les installations, remplacement de chauffe-eau, plomberie de salle de bain et réparations planifiées — avec le soin technique que les travaux sérieux méritent.',
      cta1: 'Demander un devis',
      cta2: 'Appeler {businessName}',
      tags: ['Installation', 'Remplacement', 'Confort eau', 'Étape suivante claire'],
    },
    pillars: {
      tag: 'Type de travaux',
      h2: 'Réparer, remplacer, améliorer.',
      sub: "Chaque demande de plomberie n'a pas le même objectif. L'étape suivante la plus claire dépend de si la situation appelle une correction, un remplacement ou une amélioration du confort.",
      related: 'Services associés',
      cta: 'Inclure dans un devis',
      items: [
        { label: 'Réparer', num: '01', headline: 'Réparer', copy: "Fuites, canalisations bouchées et robinetterie défaillante nécessitent un premier regard clair avant tout.", detail: "Des photos et une courte description peuvent aider à clarifier les symptômes visibles.", note: 'Clarté avant engagement.' },
        { label: 'Remplacer', num: '02', headline: 'Remplacer', copy: "Chauffe-eau, robinets ou équipements sanitaires — un remplacement réussi demande du contexte, pas de la précipitation.", detail: "Le type d'équipement, l'accès et le délai peuvent changer l'étape suivante.", note: 'Le bon équipement. Le bon moment.' },
        { label: 'Améliorer', num: '03', headline: 'Améliorer', copy: "Les travaux salle de bain et installation demandent une discussion plus fine sur l'aménagement, le confort et l'usage.", detail: "Un travail planifié est plus facile à discuter quand la pièce et le résultat sont clairs.", note: 'Le confort, par conception.' },
      ],
    },
    services: {
      tag: 'Services',
      h2: 'Des services reliés par un seul fil conducteur.',
      sub: "De la première description à l'étape suivante, chaque service est abordé avec méthode et clarté.",
      also: 'Également disponible',
      include: 'Inclure dans le devis',
      items: [
        { title: 'Réparation', description: 'Pour les fuites visibles, blocages ou problèmes de robinetterie qui nécessitent une attention concrète.', bestFor: 'Pannes courantes, gêne ou symptômes récurrents.', detail: 'Décrivez quand le problème a débuté et ce qui a visiblement changé.' },
        { title: 'Chauffe-eau', description: "Pour une perte d'eau chaude, une fuite active ou un remplacement planifié — une façon plus claire de commencer.", bestFor: 'Confort eau chaude, planification de remplacement, problèmes visibles.', detail: "Des photos de l'équipement peuvent clarifier la demande." },
        { title: 'Salle de bain', description: 'Pour robinets, douches, WC, évacuation ou changement d\'équipements liés au confort de la salle de bain.', bestFor: 'Travaux planifiés, remplacement d\'équipements, usage quotidien.', detail: 'Précisez si le travail est une réparation, un remplacement ou une amélioration.' },
        { title: 'Installation', description: 'Pour des travaux de plomberie planifiés qui nécessitent un brief clair avant tout engagement.', bestFor: 'Nouveaux équipements, modifications de configuration, raccordements.', detail: 'Des photos de la pièce et le délai souhaité donnent un meilleur point de départ.' },
      ],
    },
    quote: {
      tag: 'Demande de devis',
      h2a: 'Un meilleur devis commence',
      h2b: 'par de meilleurs détails.',
      sub: 'Un travail de plomberie planifié est plus facile à clarifier quand le premier message contient les informations essentielles.',
      urgentNote: "Pour les problèmes urgents, appeler est souvent plus direct qu'un formulaire.",
      briefTitle: 'Brief travaux',
      prompts: [
        { label: 'Quoi', text: 'Qu\'est-ce qui doit être réparé, remplacé ou installé ?' },
        { label: 'Où', text: 'Où se situe le problème dans le logement ?' },
        { label: 'Urgence', text: 'Est-ce urgent ou peut-on le planifier ?' },
        { label: 'Photos', text: "Pouvez-vous envoyer des photos du problème visible ou de l'équipement ?" },
        { label: 'Timing', text: 'Quel délai conviendrait le mieux ?' },
      ],
      form: { name: 'Nom', namePh: 'Votre nom', phone: 'Téléphone', email: 'Email', area: 'Quartier / Ville', areaPh: 'Votre quartier ou ville', type: 'Type de travaux', typePh: 'Sélectionner un type', options: ['Réparation','Remplacement','Installation / Amélioration','Chauffe-eau','Plomberie salle de bain','Autre'], message: 'Message', messagePh: 'Décrivez les travaux ou le problème en quelques mots', photos: 'Photos (optionnel)', photosPh: "Cliquez pour joindre des photos des travaux ou de l'équipement", send: 'Envoyer le brief', foot: "Les détails des travaux aident à clarifier l'étape suivante." },
    },
    comfort: {
      tag: 'Confort',
      h2a: 'Le confort se cache souvent',
      h2b: 'dans les détails.',
      sub: "La pression d'eau, l'eau chaude fiable, la robinetterie, l'évacuation, l'accès et les choix d'installation façonnent le ressenti d'une salle de bain au quotidien.",
      items: [
        { label: "Pression d'eau", sub: 'Constante, confortable, correcte.' },
        { label: 'Eau chaude fiable', sub: 'Chaque matin. À chaque fois.' },
        { label: 'Robinetterie propre', sub: 'Installée avec soin et méthode.' },
        { label: 'Confort salle de bain', sub: 'Conçu autour du quotidien.' },
        { label: 'Remplacement planifié', sub: 'Avant que ça devienne un problème.' },
      ],
      projectTypes: 'Types de travaux',
      cta: 'Demander un devis',
      caption: 'Vue salle de bain — illustrative',
    },
    process: {
      tag: 'Processus',
      h2a: 'Du premier contact',
      h2b: 'au travail planifié.',
      sub: 'Moins de confusion avant le démarrage. Un processus clair signifie un meilleur brief, un meilleur devis et un meilleur résultat.',
      cta: 'Demander un devis',
      avail: 'La disponibilité peut varier selon le planning et la zone.',
      steps: [
        { num: '01', title: 'Premier contact', copy: 'Appelez ou envoyez une courte description. Quelques mots suffisent pour commencer.', tag: 'Initier' },
        { num: '02', title: 'Photos ou détails', copy: "Des photos d'équipement, étiquettes ou de la pièce permettent de clarifier rapidement la situation.", tag: 'Documenter' },
        { num: '03', title: 'Définition du périmètre', copy: "Comprendre si le travail est une réparation, un remplacement ou une amélioration oriente l'étape suivante.", tag: 'Clarifier' },
        { num: '04', title: 'Devis ou suite', copy: "Pour un travail planifié, l'étape suivante est plus claire quand le brief est précis.", tag: 'Discuter' },
        { num: '05', title: 'Intervention planifiée', copy: 'Le travail commence avec un brief clair, pas un appel précipité.', tag: 'Exécuter' },
      ],
    },
    local: {
      tag: 'Présence locale',
      h2: 'Basé autour de {city}',
      sub: "Interventions de plomberie et demandes autour de {city}, selon disponibilité et contexte des travaux.",
      note: 'Mentionnez votre zone lors d\'un appel ou d\'une demande de devis. La disponibilité peut varier selon le planning et la localisation.',
    },
    faq: {
      tag: 'FAQ',
      h2a: 'Questions avant',
      h2b: 'de commencer',
      items: [
        { q: 'Vaut-il mieux appeler ou demander un devis ?', a: 'Pour les problèmes urgents, appeler est généralement plus direct. Pour les travaux planifiés, remplacements ou travaux de salle de bain, une demande de devis permet de décrire les travaux plus précisément.' },
        { q: 'Puis-je envoyer des photos avant une visite ?', a: "Les photos permettent de clarifier les équipements, chauffe-eau, fuites visibles, conditions d'accès et le contexte général — souvent plus efficacement qu'une description écrite seule." },
        { q: 'Vous occupez-vous du remplacement de chauffe-eau ?', a: "Consultez la liste des services sur cette page. Si le remplacement de chauffe-eau y figure, il peut être inclus dans une demande de devis. Le type d'équipement et les conditions d'accès aident à préciser l'étape suivante." },
        { q: 'Intervenez-vous autour de {city} ?', a: '{businessName} traite les demandes de plomberie autour de {city} et certaines zones proches. La disponibilité peut varier selon le planning et le contexte des travaux.' },
      ],
    },
    finalCta: {
      tag: 'Demande de travaux',
      h2a: 'Des travaux de plomberie',
      h2b: 'à {city} ?',
      sub: "Envoyez les informations essentielles — {businessName} clarifiera la suite avec soin.",
      cta: 'Demander un devis',
      call: 'Appeler',
      line: 'Détails clairs. Suite plus nette.',
    },
    footer: {
      sub: "Plomberie à {city}.\nInstallation, remplacement et confort eau — avec soin technique.",
      contact: 'Contact',
      areas: 'Zones',
      privacy: 'Politique de confidentialité',
      legal: 'Mentions légales',
    },
    mobile: { quote: 'Devis', call: 'Appeler' },
  },

  en: {
    nav: ['Services', 'Quote', 'Areas', 'FAQ'],
    cta: 'Request a quote',
    hero: {
      eyebrow: 'Plumbing in {city}',
      h1a: 'Plumbing work',
      h1b: 'designed to last.',
      sub: '{businessName} handles installations, water heater replacements, bathroom plumbing and planned repairs — with the technical care that serious work deserves.',
      cta1: 'Request a quote',
      cta2: 'Call {businessName}',
      tags: ['Installation', 'Replacement', 'Water comfort', 'Clear next step'],
    },
    pillars: {
      tag: 'Type of work',
      h2: 'Repair, replace, improve.',
      sub: "Not every plumbing request has the same goal. The clearest next step depends on whether the situation calls for correction, replacement or a comfort upgrade.",
      related: 'Related services',
      cta: 'Include in a quote',
      items: [
        { label: 'Repair', num: '01', headline: 'Repair', copy: 'Leaks, blocked drains and failing fixtures need a clear first look before anything else.', detail: 'Photos and a short description can help clarify visible symptoms before the first step.', note: 'Clarity before commitment.' },
        { label: 'Replace', num: '02', headline: 'Replace', copy: 'Water heaters, taps or sanitary fixtures should be replaced with context, not rushed blindly.', detail: 'Equipment type, access and timing can change the next step significantly.', note: 'Right equipment. Right moment.' },
        { label: 'Improve', num: '03', headline: 'Improve', copy: 'Bathroom and installation work needs a cleaner conversation around layout, comfort and long-term use.', detail: 'Planned work is easier to discuss when room, fixtures and the desired result are clear.', note: 'Comfort, by design.' },
      ],
    },
    services: {
      tag: 'Services',
      h2: 'Services connected by one clear flow.',
      sub: 'From the first description to the next step, each service is approached with method and clarity.',
      also: 'Also available',
      include: 'Include in quote request',
      items: [
        { title: 'Repair', description: 'For visible leaks, blocked flow or fixture problems that need practical attention.', bestFor: 'Everyday faults, discomfort or recurring symptoms.', detail: 'Describe when the issue started and what has visibly changed.' },
        { title: 'Water heater', description: 'For loss of hot water, active leaks or a planned replacement — a clearer way to begin.', bestFor: 'Hot water comfort, replacement planning, visible unit issues.', detail: 'Photos of the unit and visible labels can clarify the request.' },
        { title: 'Bathroom plumbing', description: 'For taps, showers, WC, drainage or fixture changes tied to bathroom comfort.', bestFor: 'Planned work, fixture replacement, bathroom usability.', detail: 'Mention whether the work is repair, replacement or improvement.' },
        { title: 'Installation', description: 'For planned plumbing work that needs a clear brief before any commitment.', bestFor: 'New fixtures, layout changes, equipment connection.', detail: 'Room photos and desired timing give a cleaner starting point.' },
      ],
    },
    quote: {
      tag: 'Quote request',
      h2a: 'A better quote starts',
      h2b: 'with better details.',
      sub: 'Planned plumbing work is easier to clarify when the first message contains the essential information.',
      urgentNote: 'For urgent problems, calling may be clearer than a form.',
      briefTitle: 'Project brief',
      prompts: [
        { label: 'What', text: 'What needs to be repaired, replaced or installed?' },
        { label: 'Where', text: 'Where is the issue located in the home?' },
        { label: 'Urgency', text: 'Is it urgent or can it be planned?' },
        { label: 'Photos', text: 'Can you send photos of the visible issue or equipment?' },
        { label: 'Timing', text: 'What timing would work best?' },
      ],
      form: { name: 'Name', namePh: 'Your name', phone: 'Phone', email: 'Email', area: 'Area', areaPh: 'Your neighbourhood or city', type: 'Type of work', typePh: 'Select a type', options: ['Repair','Replacement','Installation / Improvement','Water heater','Bathroom plumbing','Other'], message: 'Message', messagePh: 'Describe the work or issue in a few words', photos: 'Photos (optional)', photosPh: 'Click to attach photos of the work or equipment', send: 'Send brief', foot: 'Details help clarify the next step.' },
    },
    comfort: {
      tag: 'Comfort',
      h2a: 'Comfort is often',
      h2b: 'hidden in the details.',
      sub: 'Water pressure, reliable hot water, clean fixtures, drainage, access and installation choices all shape how a bathroom feels day after day.',
      items: [
        { label: 'Water pressure', sub: 'Consistent, comfortable, correct.' },
        { label: 'Reliable hot water', sub: 'Every morning. Every time.' },
        { label: 'Clean fixtures', sub: 'Installed with care and method.' },
        { label: 'Bathroom usability', sub: 'Designed around daily use.' },
        { label: 'Planned replacement', sub: 'Before it becomes a problem.' },
      ],
      projectTypes: 'Types of work',
      cta: 'Request a quote',
      caption: 'Bathroom plan — illustrative',
    },
    process: {
      tag: 'Process',
      h2a: 'From first contact',
      h2b: 'to planned work.',
      sub: 'Less confusion before the work starts. A clear process means a better brief, a better quote and a better outcome.',
      cta: 'Request a quote',
      avail: 'Availability may vary depending on schedule and location.',
      steps: [
        { num: '01', title: 'First contact', copy: 'Call or send a short description. A few words are enough to start.', tag: 'Initiate' },
        { num: '02', title: 'Photos or details', copy: 'Fixtures, equipment labels or room photos can clarify the situation quickly.', tag: 'Document' },
        { num: '03', title: 'Scope clarification', copy: 'Understanding whether the work is repair, replacement or improvement shapes the next step.', tag: 'Clarify' },
        { num: '04', title: 'Quote or next step', copy: 'For planned work, the next step is clearer when the brief is specific.', tag: 'Discuss' },
        { num: '05', title: 'Planned intervention', copy: 'Work begins with a clear brief, not a rushed call.', tag: 'Execute' },
      ],
    },
    local: {
      tag: 'Local presence',
      h2: 'Based around {city}',
      sub: 'Plumbing work and service requests around {city}, depending on availability and project context.',
      note: 'Mention your area when calling or requesting a quote. Availability may vary depending on schedule and location.',
    },
    faq: {
      tag: 'FAQ',
      h2a: 'Questions before',
      h2b: 'starting',
      items: [
        { q: 'Should I call or request a quote?', a: 'For urgent issues, calling is usually clearer. For planned installations, replacements or bathroom work, a quote request helps describe the work more precisely and gets a cleaner response.' },
        { q: 'Can I send photos before a visit?', a: 'Photos can clarify fixtures, water heaters, visible leaks, access conditions and the general context — often more effectively than a written description alone.' },
        { q: 'Do you handle water heater replacement?', a: 'Check the service list on this page. If water heater replacement is listed, it can be included in a quote request. Equipment type and access conditions help clarify the next step.' },
        { q: 'Do you work around {city}?', a: '{businessName} handles plumbing enquiries around {city} and selected nearby areas. Availability may vary depending on schedule and project context.' },
      ],
    },
    finalCta: {
      tag: 'Work request',
      h2a: 'Planning plumbing work',
      h2b: 'in {city}?',
      sub: 'Send the essential details — {businessName} will clarify the next step with care.',
      cta: 'Request a quote',
      call: 'Call',
      line: 'Clear details. Cleaner next step.',
    },
    footer: {
      sub: "Plumbing in {city}.\nInstallation, replacement and water comfort — with technical care.",
      contact: 'Contact',
      areas: 'Areas',
      privacy: 'Privacy policy',
      legal: 'Legal notice',
    },
    mobile: { quote: 'Quote', call: 'Call' },
  },

  es: {
    nav: ['Servicios', 'Presupuesto', 'Zonas', 'FAQ'],
    cta: 'Solicitar presupuesto',
    hero: {
      eyebrow: 'Fontanería en {city}',
      h1a: 'Fontanería diseñada',
      h1b: 'para durar.',
      sub: '{businessName} se encarga de instalaciones, sustitución de calentadores, fontanería de baño y reparaciones planificadas — con el cuidado técnico que los trabajos serios merecen.',
      cta1: 'Solicitar presupuesto',
      cta2: 'Llamar a {businessName}',
      tags: ['Instalación', 'Sustitución', 'Confort de agua', 'Siguiente paso claro'],
    },
    pillars: {
      tag: 'Tipo de trabajo',
      h2: 'Reparar, sustituir, mejorar.',
      sub: "No todas las solicitudes de fontanería tienen el mismo objetivo. El siguiente paso más claro depende de si la situación requiere una corrección, una sustitución o una mejora del confort.",
      related: 'Servicios relacionados',
      cta: 'Incluir en presupuesto',
      items: [
        { label: 'Reparar', num: '01', headline: 'Reparar', copy: 'Las fugas, tuberías obstruidas y grifería defectuosa necesitan una primera inspección clara antes de cualquier otra cosa.', detail: 'Las fotos y una breve descripción pueden ayudar a clarificar los síntomas visibles.', note: 'Claridad antes del compromiso.' },
        { label: 'Sustituir', num: '02', headline: 'Sustituir', copy: 'Los calentadores, grifos o equipos sanitarios deben sustituirse con contexto, no con precipitación.', detail: 'El tipo de equipo, el acceso y el plazo pueden cambiar el siguiente paso.', note: 'El equipo correcto. El momento correcto.' },
        { label: 'Mejorar', num: '03', headline: 'Mejorar', copy: 'Los trabajos de baño e instalación requieren una conversación más detallada sobre distribución, confort y uso.', detail: 'Un trabajo planificado es más fácil de discutir cuando el espacio y el resultado deseado están claros.', note: 'Confort, por diseño.' },
      ],
    },
    services: {
      tag: 'Servicios',
      h2: 'Servicios conectados por un hilo conductor.',
      sub: 'Desde la primera descripción hasta el siguiente paso, cada servicio se aborda con método y claridad.',
      also: 'También disponible',
      include: 'Incluir en presupuesto',
      items: [
        { title: 'Reparación', description: 'Para fugas visibles, obstrucciones o problemas de grifería que necesitan atención práctica.', bestFor: 'Averías comunes, molestias o síntomas recurrentes.', detail: 'Describa cuándo comenzó el problema y qué ha cambiado visiblemente.' },
        { title: 'Calentador', description: 'Para pérdida de agua caliente, fugas activas o una sustitución planificada — una forma más clara de empezar.', bestFor: 'Confort de agua caliente, planificación de sustitución, problemas visibles.', detail: 'Las fotos del equipo y las etiquetas visibles pueden clarificar la solicitud.' },
        { title: 'Fontanería de baño', description: 'Para grifos, duchas, WC, desagüe o cambios de equipos relacionados con el confort del baño.', bestFor: 'Trabajos planificados, sustitución de equipos, funcionalidad del baño.', detail: 'Indique si el trabajo es una reparación, sustitución o mejora.' },
        { title: 'Instalación', description: 'Para trabajos de fontanería planificados que necesitan un brief claro antes de cualquier compromiso.', bestFor: 'Nuevos equipos, cambios de distribución, conexión de equipos.', detail: 'Las fotos de la habitación y el plazo deseado dan un mejor punto de partida.' },
      ],
    },
    quote: {
      tag: 'Solicitud de presupuesto',
      h2a: 'Un mejor presupuesto empieza',
      h2b: 'con mejores detalles.',
      sub: 'Un trabajo de fontanería planificado es más fácil de clarificar cuando el primer mensaje contiene la información esencial.',
      urgentNote: 'Para problemas urgentes, llamar puede ser más directo que un formulario.',
      briefTitle: 'Brief del trabajo',
      prompts: [
        { label: 'Qué', text: '¿Qué hay que reparar, sustituir o instalar?' },
        { label: 'Dónde', text: '¿Dónde está el problema en el domicilio?' },
        { label: 'Urgencia', text: '¿Es urgente o se puede planificar?' },
        { label: 'Fotos', text: '¿Puede enviar fotos del problema visible o del equipo?' },
        { label: 'Plazo', text: '¿Qué plazo sería más conveniente?' },
      ],
      form: { name: 'Nombre', namePh: 'Su nombre', phone: 'Teléfono', email: 'Email', area: 'Barrio / Ciudad', areaPh: 'Su barrio o ciudad', type: 'Tipo de trabajo', typePh: 'Seleccionar un tipo', options: ['Reparación','Sustitución','Instalación / Mejora','Calentador','Fontanería de baño','Otro'], message: 'Mensaje', messagePh: 'Describa el trabajo o el problema en pocas palabras', photos: 'Fotos (opcional)', photosPh: 'Haga clic para adjuntar fotos del trabajo o del equipo', send: 'Enviar brief', foot: 'Los detalles del trabajo ayudan a clarificar el siguiente paso.' },
    },
    comfort: {
      tag: 'Confort',
      h2a: 'El confort a menudo',
      h2b: 'está en los detalles.',
      sub: 'La presión del agua, el agua caliente fiable, la grifería, el desagüe, el acceso y las opciones de instalación determinan cómo se siente un baño día tras día.',
      items: [
        { label: 'Presión del agua', sub: 'Constante, cómoda, correcta.' },
        { label: 'Agua caliente fiable', sub: 'Cada mañana. Siempre.' },
        { label: 'Grifería cuidada', sub: 'Instalada con cuidado y método.' },
        { label: 'Confort de baño', sub: 'Diseñado para el uso diario.' },
        { label: 'Sustitución planificada', sub: 'Antes de que se convierta en problema.' },
      ],
      projectTypes: 'Tipos de trabajo',
      cta: 'Solicitar presupuesto',
      caption: 'Plano de baño — ilustrativo',
    },
    process: {
      tag: 'Proceso',
      h2a: 'Del primer contacto',
      h2b: 'al trabajo planificado.',
      sub: 'Menos confusión antes de empezar. Un proceso claro significa un mejor brief, un mejor presupuesto y un mejor resultado.',
      cta: 'Solicitar presupuesto',
      avail: 'La disponibilidad puede variar según el calendario y la ubicación.',
      steps: [
        { num: '01', title: 'Primer contacto', copy: 'Llame o envíe una breve descripción. Unas pocas palabras son suficientes para empezar.', tag: 'Iniciar' },
        { num: '02', title: 'Fotos o detalles', copy: 'Las fotos de equipos, etiquetas o de la habitación pueden clarificar la situación rápidamente.', tag: 'Documentar' },
        { num: '03', title: 'Definición del alcance', copy: 'Entender si el trabajo es una reparación, sustitución o mejora orienta el siguiente paso.', tag: 'Clarificar' },
        { num: '04', title: 'Presupuesto o siguiente paso', copy: 'Para un trabajo planificado, el siguiente paso es más claro cuando el brief es específico.', tag: 'Discutir' },
        { num: '05', title: 'Intervención planificada', copy: 'El trabajo comienza con un brief claro, no con una llamada apresurada.', tag: 'Ejecutar' },
      ],
    },
    local: {
      tag: 'Presencia local',
      h2: 'Con base en {city}',
      sub: 'Trabajos de fontanería y solicitudes de servicio alrededor de {city}, según disponibilidad y contexto.',
      note: 'Mencione su zona al llamar o solicitar presupuesto. La disponibilidad puede variar según el calendario y la ubicación.',
    },
    faq: {
      tag: 'FAQ',
      h2a: 'Preguntas antes',
      h2b: 'de empezar',
      items: [
        { q: '¿Es mejor llamar o solicitar presupuesto?', a: 'Para problemas urgentes, llamar suele ser más directo. Para instalaciones planificadas, sustituciones o trabajos de baño, una solicitud de presupuesto ayuda a describir el trabajo con más precisión.' },
        { q: '¿Puedo enviar fotos antes de una visita?', a: 'Las fotos pueden clarificar equipos, calentadores, fugas visibles, condiciones de acceso y el contexto general — a menudo de forma más eficaz que una descripción escrita.' },
        { q: '¿Se encargan de la sustitución de calentadores?', a: 'Consulte la lista de servicios en esta página. Si la sustitución de calentadores aparece, puede incluirse en una solicitud de presupuesto. El tipo de equipo y las condiciones de acceso ayudan a clarificar el siguiente paso.' },
        { q: '¿Trabajan en la zona de {city}?', a: '{businessName} atiende solicitudes de fontanería en {city} y zonas cercanas. La disponibilidad puede variar según el calendario y el contexto del trabajo.' },
      ],
    },
    finalCta: {
      tag: 'Solicitud de trabajo',
      h2a: '¿Trabajos de fontanería',
      h2b: 'en {city}?',
      sub: 'Envíe los detalles esenciales — {businessName} clarificará el siguiente paso con cuidado.',
      cta: 'Solicitar presupuesto',
      call: 'Llamar',
      line: 'Detalles claros. Siguiente paso más nítido.',
    },
    footer: {
      sub: "Fontanería en {city}.\nInstalación, sustitución y confort de agua — con cuidado técnico.",
      contact: 'Contacto',
      areas: 'Zonas',
      privacy: 'Política de privacidad',
      legal: 'Aviso legal',
    },
    mobile: { quote: 'Presupuesto', call: 'Llamar' },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('fr');
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}